version: '3'
services:
  postservice1:
    hostname: postservice1
    image: dokeydokey666/postservice
    build:
      context: .
      dockerfile: "Dockerfile"
  postservice2:
    hostname: postservice2
    image: dokeydokey666/postservice
    build:
      context: .
      dockerfile: "Dockerfile"
  postservice3:
    hostname: postservice3
    image: dokeydokey666/postservice
    build:
      context: .
      dockerfile: "Dockerfile"

